---
type: zero-touch

default_width: 30
persist_url_state: true

view_switcher:
  enabled: true
  default_mode: split

tabs:
- name: OpenShift Console
  url: 'https://console-openshift-console.${DOMAIN}'
- name: Terminal
  path: /wetty
  port: 443

antora:
  name: modules
  dir: www
  modules:
  - name: pxe-osv-01
    label: "Storage Classes and Storage Profiles"
    scripts: [solve, validation]
    solveButton: true
  - name: pxe-osv-02
    label: "Persistent Storage Volume Provisioning (1)"
    scripts: [solve, validation]
    solveButton: true
  - name: pxe-osv-03
    label: "Persistent Storage Volume Provisioning (2)"
    scripts: [solve, validation]
    solveButton: true
  - name: pxe-osv-04
    label: "Virtual Machine Snapshots"
    scripts: [solve, validation]
    solveButton: true
  - name: pxe-osv-05
    label: "Automatic Storage Management with Autopilot"
    scripts: [solve, validation]
    solveButton: true
